#pragma once
const int ledcount = 150; // LED count for WS2812B
const int imageHeight = 32; //Your matrix height
const int imageWidth = 64; //Your matrix width
const int pixelCount = imageHeight * imageWidth;
int MATRIX_BRIGHTNESS = 255;
int LED_BRIGHTNESS = 60;
int hueOffset = 0; // Not needed to be modified
int wavelength = 2; // Default value is 1, is how many waves are shown?
int frame_delay = 10;
int animation_delay = 4; // Idk why it needs to be separate: 2024
int loopEvent = 2;
int xsine_period = 4; // (360/b)
int xsine_amp = 3; // mulitiplier
int xsine_phase = 0;
int xsine_offset = 0;
int ysine_offset = 0;
int ysine_period = 3; // to be adjusted
int ysine_amp = 4; // to also be adjusted
